apiVersion: v2
name: kubecron
description: Monitor Kubernetes CronJob executions across multiple clusters
type: application
version: 0.4.1
appVersion: "0.4.1"
keywords:
  - kubernetes
  - cronjob
  - monitoring
home: https://github.com/schmitech-fr/kubecron
sources:
  - https://github.com/schmitech-fr/kubecron
maintainers:
  - name: schmitech-fr
